services:

  testing:
    build:
      dockerfile: Dockerfile
    ports:
    - "${PORT_PROXY:-10000}:10000/udp"
    - "${PORT_ADMIN:-10001}:10001"

  service-udp:
    build:
      dockerfile: Dockerfile-udp
